### ISSUE TITLE
błąd groby/bany

### ISSUE THREAD

**Issue by msdaniel5** [pawelkuwa/DropSMP#35]
--> Po utracie wszystkich statystych grób jak i hologram sie pojawia ale jak zniszczymy grób (głowe gracza) to na czacie wyswietla sie kto wskrzesil a nie kogo wskrzeszono -> np Gracz Daniel zostal wskrzeszony (ale ten gracz zniszczyl glowe)
--> Bany dzialają ale jak ustawie zewnetrzna komende to banuje, ale nie wyskakuje na czacie ze ten gracz zostal zbanowany, wiec troche dziwne dla mnie.
Pozdrawiam

**Comment by pawelkuwa** [comment]
co do wiadomości o banie z zewnętrznej komendy to już odpowiada za to plugin którym posługujesz się do banowania, zakładam że to essentials, a jeżeli się nie  mylę to w essentialsie potrzebujesz permisji do otrzymywania powiadomień o karach

co do grobów to jak wrócę do domu to sprawdzę czy ten błąd występuje u mnie

**Comment by msdaniel5** [comment]
Groby nadal tak sa jak wyzej pisalem. Dodatkowo jak lootbox da sie do /mysterybox to jest nieskonczony .

**Comment by pawelkuwa** [comment]
wymieniony błąd został naprawiony w https://github.com/pawelkuwa/DropSMP/releases/tag/1.5.5, co do "Dodatkowo jak lootbox da sie do /mysterybox to jest nieskonczony ." nie rozumiem błędu opisz go wyraźniej
